#!/usr/bin/env python

import sys
from string import Template

ISRS_WITH_ERRORS = {
    8,  # DF - Double Fault
    10,  # TS - Invalid TSS
    11,  # NP - Segment Not Present
    12,  # SS - Stack-Segment Fault
    13,  # GP - General Protection Fault
    14,  # PF - Page Fault
    17,  # AC - Alignment Check
    21,  # CP - Control Protection Exception
    29,  # VC - VMM Communication Exception
    30,  # SX - Security Exception
}

TEMPLATE = r"""
# Generated by $script

.intel_syntax noprefix

.section .data

.balign 8
.global cpu_interrupt_handlers
cpu_interrupt_handlers:
$data_generated

.section .text

.extern cpu_handle_interrupt_common

.macro DEFINE_SYNTHETIC_ERROR_ISR vector
    .global cpu_handle_interrupt_\vector
    .type cpu_handle_interrupt_\vector @function
    cpu_handle_interrupt_\vector:
        push 0
        push \vector
        jmp cpu_handle_interrupt_common
.endm

.macro DEFINE_ISR vector
    .global cpu_handle_interrupt_\vector
    .type cpu_handle_interrupt_\vector @function
    cpu_handle_interrupt_\vector:
        push \vector
        jmp cpu_handle_interrupt_common
.endm

$text_generated
""".strip()


def main():
    data_strs: list[str] = []
    for i in range(256):
        data_strs.append(f"    .quad cpu_handle_interrupt_{i}")

    text_strs: list[str] = []
    for i in range(256):
        if i in ISRS_WITH_ERRORS:
            text = f"DEFINE_ISR {i}"
        else:
            text = f"DEFINE_SYNTHETIC_ERROR_ISR {i}"

        text_strs.append(text)

    print(
        Template(TEMPLATE).substitute(
            script=sys.argv[0],
            data_generated="\n".join(data_strs),
            text_generated="\n".join(text_strs),
        )
    )


if __name__ == "__main__":
    main()
